### ISSUE TITLE
Array enhancment

### ISSUE THREAD

**Issue by Dan503** [jwinfield/objgen-js#1]
Currently the way that the arrays work for arrays of objects isn't as good as the method for doing it in plain old json.

This is how objgen currently produces an array of objects:

````````
arrayKey[0]
  key = value
arrayKey[1]
  key = value
````````
to create
````````json
{
  "arrayKey": [
    {
      "key": "value"
    },
    {
      "key": "value"
    }
  ]
}
````````

There are 3 main problems with this that make plain old json superior to objgen

1. The need to manually keep track of indexes making re-ordering, adding and removing a pain
2. The need to constantly repeat the array key value over and over again
3. The inability to start a json file as an array instead of an object

This is the solution I propose:

````````
arrayKey
  []
    key = value
  []
    key = value
````````
to create
````````json
{
  "arrayKey": [
    {
      "key": "value"
    },
    {
      "key": "value"
    }
  ]
}
````````

This solve all 3 issues and will make objgen definitively the superior way to manually write json files.

It even solves the issue of being able to start with an array by doing this:

````````
[]
  key = value
[]
  key = value
````````
to create
````````json
[
  {
    "key": "value"
  },
  {
    "key": "value"
  }
]
````````

**Comment by jwinfield** [comment]
Good suggestions @Dan503 - I'll do some research on extending the syntax to accommodate these array scenarios.

**Comment by jwinfield** [comment]
PR #4 addressed the enhancements for array generation. Code has been merged to master a published to [npm](https://www.npmjs.com/package/objgen) as version 4.0.3. The online [JSON generator](http://objgen.com/json) has not yet been updated and will be as part of a larger update that's still in development.

> The need to manually keep track of indexes making re-ordering, adding and removing a pain

Fixed. You can now generate arrays without the need for indices.

> The need to constantly repeat the array key value over and over again

Won't fix this because it would introduce a change in the syntax that could cause existing models to break. May revisit.

> The inability to start a json file as an array instead of an object

Fixed. You can now generate JSON arrays using the following syntax:

```
[]
  key = 1
[]
  key = 2
```

to create:

```js
[
  {
    "key": "1"
  },
  {
    "key": "2"
  }
]
```

**Comment by Dan503** [comment]
"Won't fix this because it would introduce a change in the syntax that could cause existing models to break."

Couldn't this have been released as a new major version? That would prevent people's code from breaking since major versions mean "introduces breaking changes".

... but since this version of the syntax didn't exist before, I don't see how this would be a breaking change if you still support the old method.

**Comment by Dan503** [comment]
> The need to constantly repeat the array key value over and over again

That is an incredibly annoying part of using this syntax and needs to be addressed to make this better than just writing regular json.
Without that feature, this syntax still isn't worth using.
